"""
Lookbook Service for JewelClaw.

Generates PDF lookbooks from user's saved designs.
"""

import logging
import io
import httpx
from datetime import datetime
from typing import List, Dict, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc

from app.models import Design, Lookbook, UserDesignPreference

logger = logging.getLogger(__name__)


class LookbookService:
    """Service for generating PDF lookbooks."""

    def __init__(self):
        self.max_designs_per_lookbook = 50
        self.page_size = (595, 842)  # A4 in points
        self.margin = 50

    async def get_user_saved_designs(
        self,
        db: AsyncSession,
        user_id: int,
        limit: int = 50
    ) -> List[Design]:
        """Get user's saved/liked designs."""
        result = await db.execute(
            select(Design)
            .join(UserDesignPreference)
            .where(UserDesignPreference.user_id == user_id)
            .where(UserDesignPreference.action.in_(["liked", "saved"]))
            .order_by(desc(UserDesignPreference.created_at))
            .limit(limit)
        )
        return result.scalars().all()

    async def create_lookbook(
        self,
        db: AsyncSession,
        user_id: int,
        name: str = None,
        design_ids: List[int] = None
    ) -> Lookbook:
        """Create a new lookbook entry."""
        if not name:
            name = f"Lookbook {datetime.now().strftime('%d %b %Y')}"

        if not design_ids:
            # Get user's saved designs
            designs = await self.get_user_saved_designs(db, user_id)
            design_ids = [d.id for d in designs]

        lookbook = Lookbook(
            user_id=user_id,
            name=name,
            design_ids=design_ids
        )
        db.add(lookbook)
        await db.commit()

        return lookbook

    async def generate_pdf(
        self,
        db: AsyncSession,
        user_id: int,
        lookbook_id: int = None
    ) -> Optional[bytes]:
        """
        Generate PDF from lookbook or user's saved designs.
        Returns PDF as bytes.
        """
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.units import inch
            from reportlab.pdfgen import canvas
            from reportlab.lib import colors
            from reportlab.lib.utils import ImageReader
            from PIL import Image
        except ImportError:
            logger.error("reportlab or Pillow not installed for PDF generation")
            return None

        # Get designs
        if lookbook_id:
            lookbook = await db.get(Lookbook, lookbook_id)
            if not lookbook:
                return None
            design_ids = lookbook.design_ids or []
            result = await db.execute(
                select(Design).where(Design.id.in_(design_ids))
            )
            designs = result.scalars().all()
            title = lookbook.name
        else:
            designs = await self.get_user_saved_designs(db, user_id)
            title = f"My Jewelry Collection - {datetime.now().strftime('%d %b %Y')}"

        if not designs:
            return None

        # Create PDF in memory
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        # Title page
        c.setFont("Helvetica-Bold", 24)
        c.drawCentredString(width/2, height - 100, title)
        c.setFont("Helvetica", 14)
        c.drawCentredString(width/2, height - 130, f"{len(designs)} Designs")
        c.setFont("Helvetica-Oblique", 10)
        c.drawCentredString(width/2, height - 160, f"Generated by JewelClaw")
        c.drawCentredString(width/2, height - 175, datetime.now().strftime("%d %B %Y, %I:%M %p"))
        c.showPage()

        # Design pages (2 per page)
        designs_per_page = 2
        img_width = 200
        img_height = 200

        for i, design in enumerate(designs):
            # Start new page every 2 designs
            if i % designs_per_page == 0 and i > 0:
                c.showPage()

            # Calculate position
            position_on_page = i % designs_per_page
            y_offset = height - 100 - (position_on_page * 350)

            # Draw design info
            c.setFont("Helvetica-Bold", 14)
            c.drawString(50, y_offset, f"{i+1}. {(design.title or 'Untitled')[:40]}")

            c.setFont("Helvetica", 11)
            y_offset -= 20
            c.drawString(50, y_offset, f"Category: {design.category or 'General'}")

            y_offset -= 15
            if design.price_range_min:
                c.drawString(50, y_offset, f"Price: Rs.{design.price_range_min:,.0f}")
            else:
                c.drawString(50, y_offset, "Price: On Request")

            y_offset -= 15
            c.drawString(50, y_offset, f"Source: {design.source}")

            # Try to add image
            if design.image_url:
                try:
                    # Fetch image
                    async with httpx.AsyncClient(timeout=10) as client:
                        response = await client.get(design.image_url)
                        if response.status_code == 200:
                            img_data = io.BytesIO(response.content)
                            img = Image.open(img_data)

                            # Convert to RGB if needed
                            if img.mode in ('RGBA', 'P'):
                                img = img.convert('RGB')

                            # Resize maintaining aspect ratio
                            img.thumbnail((img_width, img_height))

                            # Save to buffer
                            img_buffer = io.BytesIO()
                            img.save(img_buffer, format='JPEG')
                            img_buffer.seek(0)

                            # Draw image
                            c.drawImage(
                                ImageReader(img_buffer),
                                350, y_offset - img_height + 50,
                                width=img_width,
                                height=img_height,
                                preserveAspectRatio=True
                            )
                except Exception as e:
                    logger.warning(f"Failed to add image for design {design.id}: {e}")
                    # Draw placeholder
                    c.setStrokeColor(colors.grey)
                    c.rect(350, y_offset - img_height + 50, img_width, img_height)
                    c.setFont("Helvetica-Oblique", 10)
                    c.drawCentredString(350 + img_width/2, y_offset - img_height/2 + 50, "Image unavailable")

            # Draw separator line
            y_offset -= 50
            c.setStrokeColor(colors.lightgrey)
            c.line(50, y_offset, width - 50, y_offset)

        # Final page with footer
        c.showPage()
        c.setFont("Helvetica-Bold", 14)
        c.drawCentredString(width/2, height/2 + 30, "Thank you for using JewelClaw!")
        c.setFont("Helvetica", 11)
        c.drawCentredString(width/2, height/2, "Your AI-powered jewelry assistant")
        c.setFont("Helvetica-Oblique", 10)
        c.drawCentredString(width/2, height/2 - 30, "Send 'trends' for more designs")

        c.save()
        buffer.seek(0)
        return buffer.getvalue()

    async def generate_simple_pdf(
        self,
        db: AsyncSession,
        user_id: int
    ) -> Optional[bytes]:
        """
        Generate a simple text-based PDF (fallback if reportlab images fail).
        """
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.pdfgen import canvas
            from reportlab.lib import colors
        except ImportError:
            logger.error("reportlab not installed")
            return None

        designs = await self.get_user_saved_designs(db, user_id)
        if not designs:
            return None

        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        # Title
        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(width/2, height - 50, "My Jewelry Lookbook")
        c.setFont("Helvetica", 12)
        c.drawCentredString(width/2, height - 75, f"{len(designs)} Saved Designs")
        c.drawCentredString(width/2, height - 95, datetime.now().strftime("%d %B %Y"))

        y = height - 140
        c.setStrokeColor(colors.grey)
        c.line(50, y, width-50, y)
        y -= 30

        for i, design in enumerate(designs):
            if y < 100:
                c.showPage()
                y = height - 50

            c.setFont("Helvetica-Bold", 12)
            c.drawString(50, y, f"{i+1}. {(design.title or 'Untitled')[:50]}")
            y -= 18

            c.setFont("Helvetica", 10)
            price = f"Rs.{design.price_range_min:,.0f}" if design.price_range_min else "Price on request"
            c.drawString(70, y, f"{design.category or 'General'} | {price} | {design.source}")
            y -= 25

            c.setStrokeColor(colors.lightgrey)
            c.line(50, y, width-50, y)
            y -= 20

        c.save()
        buffer.seek(0)
        return buffer.getvalue()

    def format_lookbook_list(self, lookbooks: List[Lookbook]) -> str:
        """Format lookbook list for WhatsApp."""
        if not lookbooks:
            return """📚 *Your Lookbooks*

No lookbooks yet.

_Save designs with 'like [id]' then use 'create lookbook' to make a PDF_"""

        lines = ["📚 *Your Lookbooks*", ""]

        for lb in lookbooks:
            design_count = len(lb.design_ids) if lb.design_ids else 0
            date_str = lb.created_at.strftime("%d %b") if lb.created_at else ""
            lines.append(f"• {lb.name} ({design_count} designs) - {date_str}")

        lines.append("")
        lines.append("_Reply 'pdf' to generate your lookbook PDF_")

        return "\n".join(lines)


# Global instance
lookbook_service = LookbookService()
